export const ORDER_STATUS_PENDING = 'Pending';
export const ORDER_STATUS_PROCESSING = 'Processing';
export const ORDER_STATUS_SHIPPING = 'Shipping';
export const ORDER_STATUS_SHIPPED = 'Shipped';
export const ORDER_STATUS_CANCELLED = 'Cancelled';

export const ORDER_STATUS = [
  ORDER_STATUS_PENDING,
  ORDER_STATUS_PROCESSING,
  ORDER_STATUS_SHIPPING,
  ORDER_STATUS_SHIPPED,
  ORDER_STATUS_CANCELLED,
];